[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "fcbyk"
version = "0.0.0-alpha.1"
requires-python = ">=3.7"
dependencies = [
    "click",
    "flask",
    "pyperclip"
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
    "beautifulsoup4"
]

[project.scripts]
fcbyk = "fcbyk.cli:cli"

[tool.hatch.build.targets.wheel]
packages = ["src/fcbyk"]

[tool.pytest.ini_options]
testpaths = ["src/fcbyk/tests"]
python_files = ["test_*.py"]
addopts = "-v --cov=fcbyk --cov-report=term-missing" 