"""应用配置存储协议。"""

from __future__ import annotations

from typing import Any, Protocol


class ConfigStore(Protocol):
    """配置存储协议。"""

    def load(self) -> dict[str, Any]: ...
    def save(self, data: dict[str, Any]) -> None: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def set(self, key: str, value: Any) -> dict[str, Any]: ...
    def delete(self, key: str) -> dict[str, Any]: ...
